### ISSUE TITLE
Validate project

### ISSUE THREAD

**Issue by hugomaiavieira** [hugomaiavieira/kanban-roots#34]
This will be necessary when prettify the urls.
- name only with letters, numbers, _ and -
- before save, downcase
- project name should be unique for contributor

**Comment by rodrigomanhaes** [comment]
Should project name be unique for contributor or owner?

**Comment by hugomaiavieira** [comment]
Yes. My intention is change the routes to be like github's. So, project name should be routable.
What do you think?

**Comment by rodrigomanhaes** [comment]
So, the uniqueness is only related to the owner's projects, not no-owner contributors, right?

**Comment by hugomaiavieira** [comment]
Yes.

**Comment by rodrigomanhaes** [comment]
Closed by fb4ff1b9bcc86375052b to 46d76cf5be3730e6a5ab.
