### ISSUE TITLE
Remove selenium drag_and_drop deprecation warning

### ISSUE THREAD

**Issue by hugomaiavieira** [hugomaiavieira/kanban-roots#53]
Selenium::WebDriver::Element#drag_and_drop_{by,on} is deprecated. Please use Selenium::WebDriver::Driver#action (and Selenium::WebDriver::ActionBuilder) instead.

**Comment by rodrigomanhaes** [comment]
This issue was already solved (jnicklas/capybara#406), but it's very recent and there's no packed version for now.
